### ISSUE TITLE
关于优酷加密视频如何下载

### ISSUE THREAD

**Issue by Vicyyw** [soimort/you-get#1034]
上个月还可以的，今天下载发现要输入密码，可以解决吗

input url: --debug http://v.youku.com/v_show/id_XMTUyNDQwODIxMg==.html

Password:

**Comment by sd95** [comment]
这样的。现在不能下了吗？
python you-get -formar mp4 http://v.youku.com/v_show/id_XNTE5NzU4MDIw.html

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by Vicyyw** [comment]
@sd95  那个视频已经被屏蔽了，试试这个http://v.youku.com/v_show/id_XMzk0NTAyOTk2.html 我的输出还是要输入密码···

**Comment by soimort** [comment]
所以你需要知道密码。

**Comment by Vicyyw** [comment]
好的，谢谢大大

**Comment by Vicyyw** [comment]
@soimort  好的，谢谢大大，可能是我记错了

**Comment by lantianshijie** [comment]
![qq 20171011230509](https://user-images.githubusercontent.com/32711485/31449325-2de94492-aed9-11e7-99a9-5dd5aada25b6.png)
