### ISSUE TITLE
是不是爱奇艺的key过期了？看不懂啊

### ISSUE THREAD

**Issue by shanmm** [soimort/you-get#1067]
E:\Mov>you-get http://www.iqiyi.com/v_19rrlq7p9k.html#vfrm=2-3-0-1
you-get: [error] outdated iQIYI key
you-get: is your you-get up-to-date?
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

E:\Mov>

**Comment by shanmm** [comment]
@ @soimort-bot 好的

**Comment by shanmm** [comment]
@soimort-bot 怎么让他在一行跳，而不是一直跳？
比如：
40.8% (196.8/481.9MB) ├████████████████────
40.9% (197.0/481.9MB) ├████████████████────
40.9% (197.3/481.9MB) ├████████████████────
41.0% (197.5/481.9MB) ├████████████████────
41.0% (197.8/481.9MB) ├████████████████────
41.1% (198.0/481.9MB) ├████████████████────
41.1% (198.3/481.9MB) ├████████████████────
41.2% (198.5/481.9MB) ├████████████████────
41.2% (198.8/481.9MB) ├████████████████────
41.3% (199.0/481.9MB) ├████████████████────
41.3% (199.3/481.9MB) ├████████████████────
41.4% (199.5/481.9MB) ├████████████████────
41.5% (199.8/481.9MB) ├████████████████────
41.5% (200.0/481.9MB) ├████████████████────
41.6% (200.3/481.9MB) ├████████████████────
───────────┤[ 6/13]    3 MB/s
让他变成一行就行了

41.6% (200.3/481.9MB)├████████████████────这样子看着舒服

**Comment by cnbeining** [comment]
一般是你的bash的问题。

你用的是windows，有可能会有些奇妙的现象。

这个问题应该不属于```you-get```的。

Close upon request.

**Comment by soimort** [comment]
Windows cmd 下不太容易获取 screen buffer size，自己把终端调宽大概可以解决这问题。

**Comment by q6761471** [comment]
-bash: ./: is a directory
[1]+  Done                    you-get -u http://v.youku.com/v_show/id_XMjc0ODc3ODIyOA==.html?f=49726249
zhangdembp:Python 3.6 liuwu$ you-get -i http://v.youku.com/v_show/id_XMjc0ODc3ODIyOA==.html?f=49726249&spm=a2hww.20023042.m_223465.5~5~5~5~5~5~A&from=y1.3-idx-beta-1519-23042.223465.1-1
[1] 15782
[2] 15783
zhangdembp:Python 3.6 liuwu$ 
[2]+  Done                    spm=a2hww.20023042.m_223465.5~5~5~5~5~5~A
zhangdembp:Python 3.6 liuwu$ site:                优酷 (Youku)
title:               我想和你唱 170506
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          2496.4 MiB (2617677036 bytes)
    # download-with: you-get --format=hd3 [URL]

    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          1322.0 MiB (1386176453 bytes)
    # download-with: you-get --format=hd2 [URL]

    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          790.8 MiB (829193919 bytes)
    # download-with: you-get --format=mp4 [URL]

    - format:        flvhd
      container:     flv
      video-profile: 标清
      size:          384.5 MiB (403213347 bytes)
    # download-with: you-get --format=flvhd [URL]

./
-bash: ./: is a directory
[1]+  Done                    you-get -i http://v.youku.com/v_show/id_XMjc0ODc3ODIyOA==.html?f=49726249
zhangdembp:Python 3.6 liuwu$ you-get --format=hd3 http://v.youku.com/v_show/id_XMjc0ODc3ODIyOA==.html?f=49726249&spm=a2hww.20023042.m_223465.5~5~5~5~5~5~A&from=y1.3-idx-beta-1519-23042.223465.1-1
[1] 15789
[2] 15790
zhangdembp:Python 3.6 liuwu$ /
-bash: /: is a directory
[2]+  Done                    spm=a2hww.20023042.m_223465.5~5~5~5~5~5~A
zhangdembp:Python 3.6 liuwu$ ./
-bash: ./: is a directory
zhangdembp:Python 3.6 liuwu$ site:                优酷 (Youku)
title:               我想和你唱 170506
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          2496.4 MiB (2617677036 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 我想和你唱 170506.flv ...
 0.0% (   0.0/2496.4MB) ├─────────────────────────────────────┤[ 1/40] you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and repor


这是些什么错误啊
