### ISSUE TITLE
Error when I execute you-get on windows cmd

### ISSUE THREAD

**Issue by damenahito8** [soimort/you-get#1161]
I use  you-get-0.4.424-win32-full.7z ver.            
Error loading Python DLL: C:\Users\Pankzid\AppData\Local\Temp\_MEI51922\python35.dll (error code 127
)

Any suggestion ?

**Comment by soimort** [comment]
What version of Windows are you on? What exact command were you using?

**Comment by damenahito8** [comment]
Sorry, 
I' using Windows 7 pro SP1. 
you-get version: you-get-0.4.424-win32-full.7z
Command: you-get -i 'http://v.youku.com/v_show/id_XMTUzMDQ4MzQwNA==.html'
And here is the sreenshoot: http://i.imgur.com/dWW9PMJ.png

Thanks in advance.

**Comment by soimort** [comment]
The `you-get` was looking for something called `python35.dll`, but obviously it wasn't supposed to do that since everything was already pre-packaged in you-get-0.4.424-win32-full.7z (the one you use)

If you are using the 7z package, the correct way is to click on the `you-get.bat` executable (or open it with Console2 if you prefer).  You should also use `where you-get` to check which `you-get` command you're actually using.

**Comment by cnbeining** [comment]
As in https://stackoverflow.com/questions/34218333/pyinstaller-onefile-does-not-start-on-some-windows-7-machines :

>The missing hotfix is: KB2999226

**Comment by damenahito8** [comment]
Thank you for quick reply.
When I click you-get.bat. It appears error: http://i.imgur.com/mv2VP5a.png
And when run as admin: The error is: http://i.imgur.com/chkJBKo.png

@cnbeining. Thank you. I will try.

**Comment by damenahito8** [comment]
@soimort, @cnbeining Thank you, it's working now.
But I still get another error: http://i.imgur.com/WCeJhym.png

**Comment by soimort** [comment]
You should not put any single quotes around the URL. Because it's Windows.

**Comment by damenahito8** [comment]
@soimort Thank you very much. 
It's working. http://i.imgur.com/SpjmY0N.png
