### ISSUE TITLE
Can you write a list about your team, to help people ask question and contact with 

### ISSUE THREAD

**Issue by minghu6** [soimort/you-get#1182]
Can you write a list about your team, to help people ask question and contact with

**Comment by cnbeining** [comment]
No user shall expect professional support, nor should individual developer
be responsible for any part of this project.

For inquiries or questions, an issue should be raised in order to let the
whole maintainer group being updated.

For quick questions, Gitter can be used, but again no user should expect
any level of monitoring of such service.

2016年5月29日星期日，Mort the Bot <notifications@github.com> 写道：
