### ISSUE TITLE
install on mac run error

### ISSUE THREAD

**Issue by buildhappy** [soimort/you-get#1196]
mac10.11.3 
~ brew install libav
~ brew install ffmpe
~ brew install you-get
~ you-get
/usr/local/bin/you-get: /usr/local/Cellar/you-get/0.4.424/libexec/bin/you-get: /usr/local/opt/python3/bin/python3.5: bad interpreter: No such file or directory
/usr/local/bin/you-get: line 2: /usr/local/Cellar/you-get/0.4.424/libexec/bin/you-get: Undefined error: 0

**Comment by buildhappy** [comment]
It can not start up on my mac. Not related to link

**Comment by buildhappy** [comment]
What the matter?
Is it not installed?

**Comment by nuomi1** [comment]
Please [install you-get via pip3](https://github.com/soimort/you-get#option-1-install-via-pip), I don't suggest that python package has installed via homebrew because of [this](https://github.com/Homebrew/homebrew-core/commit/532c4d8705bb8224259f3efd8836bb85be3b3e74) and [this](https://github.com/Homebrew/homebrew-core/issues/1767).

**Comment by cnbeining** [comment]
Do you have Python3 installed?

**Comment by buildhappy** [comment]
Python3 installed...

**Comment by soimort** [comment]
> `/usr/local/opt/python3/bin/python3.5: bad interpreter: No such file or directory`

Most likely: your Python installation is broken. Please check if you can actually use your python interpreter (`python3.5`).
