### ISSUE TITLE
you-get -i 风行自动下载

### ISSUE THREAD

**Issue by nuomi1** [soimort/you-get#1304]
https://github.com/soimort/you-get/commit/80a8265a49a6d5b96d885023d72c3710681d19cc

```
➜  ~ you-get -i http://www.fun.tv/vplay/g-207038.v-828016/
Site:       funshion
Title:      狐妖小红娘 - 第1集
Type:       MPEG-4 video (video/mp4)
Size:       108.98 MiB (114276715 Bytes)

Downloading 狐妖小红娘 - 第1集.mp4 ...
 0.0% (  0.0/109.0MB) ├─────────────────────────────────────────┤[1/1]
```

另一个问题，http://www.fun.tv/vplay/g-207038.v-828016/ 本应当做单个视频处理，但目前的策略是当成播放列表，全部下载了。
http://www.fun.tv/vplay/g-207038/ 或 http://www.fun.tv/subject/207038/ 才是播放列表。

**Comment by soimort** [comment]
The first issue was fixed by 44c09c5; the second is yet to be resolved.

Notice: There are multiple reports about the (currentlly) broken support of fun.tv (#1004, #1039, #1184). If @cnbeining no longer wants to maintain it and no one can send a PR, the support for fun.tv may be dropped in the next release.
