### ISSUE TITLE
多线程下载视频没用？？？

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#1779]
根据我测试，发现无论是多线程还是单线程下载视频速度都差不多。
我想原因可能是视频文件通常比较大，下载器下载的时候基本都会占满带宽来下载，这时候如果还开多线程下载只不过是平均分配有限的带宽，因此最终也并不会节省视频下载时间。

以上是菜鸟我的分析，请各位大神也来发表下意见！
这个问题和本项目还是有关的，请不要随便关闭本问题，多交流下技术，共同提高！

**Comment by rosynirvana** [comment]
简而言之，只有cdn仅仅每连接限速的时候，多线程下载可以加速。

如果是按ip限速，或是cdn不主动限速，多线程下载都没效果。

**Comment by redstoneleo** [comment]
这个帖子解答的也不错http://stackoverflow.com/questions/24622038/does-downloading-with-multiple-threads-actually-speed-things-up

**Comment by rosynirvana** [comment]
stackoverflow的那个问题说的其实并不完全是一个事情，首先是线程指的是什么，JVM线程和cpython的线程差别很大，而且，这时候说的线程一般指的是tcp connection

**Comment by cnbeining** [comment]
在连接性不佳时 多个TCP连接会很有帮助。

不能只使用best case考虑。

2017年3月19日 上午6:52，"rosynirvana" <notifications@github.com>写道：

**Comment by rosynirvana** [comment]
和CDN之间没太多丢包这个不算best case只能算normal case吧

另外，host - CDN之间随机丢包用多个connection会有明显改善吗？还是说多CDN？

**Comment by cnbeining** [comment]
Depends.

一般来说 多个线程 利大于弊。

这个问题需要分站点讨论。不同的站点在不同的地理地区会很不同。


2017年3月19日 上午11:50，"rosynirvana" <notifications@github.com>写道：

和CDN之间没太多丢包这个不算best case只能算normal case吧

另外，host - CDN之间随机丢包用多个connection会有明显改善吗？还是说多CDN？

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/soimort/you-get/issues/1779#issuecomment-287625723>,
or mute
the thread

**Comment by redstoneleo** [comment]
@rosynirvana 谢谢指教！
1.cpython进行多线程IO操作的时候会释放GIL变成也是真正的多线程
2.你是咋知道百度盘的限速策略的？好猛！！！
3.你的回答结尾说“是CPython的green thread还是native thread？影响不大”，我也看了stackoverflow那个问题中的解释，不知道你所说的“影响不大”是哪些个原因？

**Comment by cnbeining** [comment]
这点速度还谈不上什么磁盘IO。

百度的策略路人皆知。

我们讨论的根本不是一个thread。不建议在issue中做和项目无关的讨论。会掉粉。


2017年3月20日 上午8:55，"redstoneleo" <notifications@github.com>写道：

@rosynirvana <https://github.com/rosynirvana> 谢谢指教！
1.cpython进行多线程IO操作的时候会释放GIL变成也是真正的多线程
2.你是咋知道百度盘的限速策略的？好猛！！！
3.你的回答结尾说“是CPython的green thread还是native thread？影响不大”，
我也看了stackoverflow那个问题中的解释，不知道你所说的“影响不大”是哪些个原因？

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/soimort/you-get/issues/1779#issuecomment-287750856>,
or mute
the thread

**Comment by rosynirvana** [comment]
@redstoneleo 

感觉你是不是还没抓住重点，下载速度和multithreading是没多大关系的，只是为了在编程中处理多个TCP connection，使用了最简单的multithreading IO模型，不用多线程模型也是可以的。

如果你想知道的是native thread为什么不影响，stackoverflow的回答：
> Downloads are network-bound, not CPU-bound. 

限速步在网络传输速度上，而不是（现在的桌面）CPU上。

这样大概回答了你第三个问题，另外第一点
> cpython进行多线程IO操作的时候会释放GIL变成也是真正的多线程

其实过度简化了问题。CPython的解释器核心部分，或者说python code是单线程的，native modules，或者说C code，可以是多线程的。

**Comment by redstoneleo** [comment]
@rosynirvana 我太菜了，谢谢！
这么看来多线程下载的主要优势是在可以实现同时下载不同的文件吧？

**Comment by rosynirvana** [comment]
@redstoneleo

只要编程上实现没问题，多线程(or multi-TCP-connections)下载很多时候都是有好处的。

1. 例如上面提到过的按连接数限速，一个连接100KiBps一般撑不满出口带宽，多个连接是能提速的；
2. 比如多CDN下载，例如bilibili的返回链接，不同分片可能有不同的CDN，那么就可能出现到某CDN的链路负载大速度慢，到某个CDN的速度快的情况

但有些好处是不是好处也不一定，例如上面的第二点，如果是等着下载看，那么其中一个分片下载好了其他分片差很多，也不一定有什么用。再比如你提到的同时下载不同的文件，如果每个下载任务单独都是满带宽，逐个下载第一个任务会在t/n后完成，就可以开始看了；如果是同时下载，那么会在时间t前后完成，用户的等待时间变得更长。

**Comment by redstoneleo** [comment]
谢谢啦

**Comment by 1048312147** [comment]
学习了

**Comment by cnbeining** [comment]
Closed due to issue not related to repo.
