### ISSUE TITLE
无法加载cookies,从0.4.900开始

### ISSUE THREAD

**Issue by a2310145622** [soimort/you-get#2351]
Please make sure these boxes are checked before submitting your issue – thank you!

- [√] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [√] Your `you-get` is up-to-date.
- [√] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [√] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [√] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [√] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [√] 您的`you-get`为最新版.
- [√] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [√] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [√] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]
C:\Users\Administrator\Desktop>you-get -c "C:\Users\Administrator\Desktop\niconico cookies.txt" http://www.nicovideo.jp/watch/sm31910935 -i --debug
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1077, in load_cookies
    cookies = cookiejar.MozillaCookieJar(a)
NameError: name 'a' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.909', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1226, in script_main
    load_cookies(args.cookies)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1082, in load_cookies
    con = sqlite3.connect(a)
NameError: name 'a' is not defined

**Comment by rosynirvana** [comment]
@soimort 
Please consider drop https://github.com/soimort/you-get/commit/35103577cf76efcdff7347fcd4c943e0db2fe0a3

moving from ```gnu_getopt``` to ```argparse``` brings more problems than it solves, if it really solves any.

**Comment by a2310145622** [comment]
使用[262b695](https://github.com/soimort/you-get/commit/262b6951c6072ecf7f5570296ca14e0789be1dfd)的common.py，可以加载cookies了

**Comment by lilydjwg** [comment]
I'm sorry about that. I definitely should run a linter before pr. I'll fix this soon.

@rosynirvana what you see is the potential issues are emerging.

**Comment by rosynirvana** [comment]
What I've seen is grammar errors brought with by a new patch, not something defected exsited in the old code.

**Comment by lilydjwg** [comment]
This kind of errors are doomed to emerge sooner or later, unless no refactoring will be performed ever. These issues also reveal the need for improvements with tests, e.g. #2145.

I'm sorry for the errors introduced, but I do think these as a cost to a better codebase. And you can see that these are of one kind: the scope is too long to split correctly. No major issues are introduced. The option parsing part is now much more declarative than iterative, and no one will ever miss a useful option in the help again. (I wouldn't spend hours to do this if nothing bugged me badly.)

**Comment by rosynirvana** [comment]
Firstly, these errors, unbound locals, are introduced at grammar level so there is no reason to blame the old code.

Secondly, ```getopt``` of GNU is the de facto standard to parse command line flags. It existed for decades and time proven. From comments in #1181 it seems that those are pushing to move to other libs do not really know about ```getopt```.

```argparse``` is much more complex with a lengthy document. It will not take anyone who knows only a little python more than 10 min to follow the old code to add a flag. The best part of ```you-get``` is that it's not so pythonic so those who only know js or as3 can take part in, moving from the universal getopt to a py-domain-specific library cannot be a nice idea.

@lilydjwg You keep saying that with ```argparse``` we won't miss a description for a command line flag. There's not so many flags to add for a 5-year-old code base. If I get it right, only 2 in the last 6 months. I've no idea what make you think keep the command line description is a tough. Even we miss one, it will only be a minor defect and possibly won't affect anyone.

**Comment by lilydjwg** [comment]
> I've no idea what make you think keep the command line description is a tough. Even we miss one, it will only be a minor defect and possibly won't affect anyone.

Because I read the help again and again to find a flag that I know you-get but failed. Then I read the source code.

> It will not take anyone who knows only a little python more than 10 min to follow the old code to add a flag

True. But they may forget that like the renaming locals thing which I've forgotten. And they won't be able to update the corresponding bash / zsh / fish completion code. (If it were help text generated by GNU getopt, there already exists a zsh completer for that. For argparse, one can be written if not yet.)

**Comment by rosynirvana** [comment]
1. Your personal experience suggests that someone forgot to update the description instead of keeping description up-to-date is a tough task

2. If only one flag is added like what is usually done within one commit, it will be well-tested. So unbound local won't happen. Shell completions are out of touch for most users. They are in the contrib folder and maintained by only one contributor. There are lots of pythonists knowing nothing about how to write shell scripts so they just cannot update them.

3 and 4. Taking the 2 sentences apart changes the original meaning. ```getopt``` is the most widely accepted way to parse command lines flags for the stdlib of most ``main-stream'' lang is heavily influnced by C-lang. F. I. ruby(```GetoptLong```) and PHP.  In the document ```getopt``` has not been labeled with deprecated, so there's no reason to call ```argparse``` more ``standard'' than ```getopt```.
What library nowaday pythonists love do not really matter here because those one know js and as3 can contribute even more in this project.

JS and as3 don't have ```getopt``` in their stdlib because they are not designed to communicate with command line. Those who only know js or as3 can contribute because ```you-get``` is not pythonic in general, not a certain library.

**Comment by rosynirvana** [comment]
This patch is premature and personal taste.
We DO have a problem about command line flags. Users can set a default HTTP proxy in their system and specified a socks proxy with comandline flags. I hope we can clean up these real problem affecting any non-develop users in China mainland, then split the project to a command line interface and a library. At that time you guys love ```argparse``` can make the move at your wish.

**Comment by lilydjwg** [comment]
On Wed, Sep 13, 2017 at 09:34:24AM -0700, rosynirvana wrote:
> 1. Your personal experience suggests that someone forgot to update the description instead of keeping description up-to-date is a tough task

It's not a tough task. It's a task that one will easily forget.

> 2. If only one flag is added like what is usually done within one commit, it will be well-tested. So unbound local won't happen. Shell completions are out of touch for most users. They are in the contrib folder and maintained by only one contributor. There are lots of pythonists knowing nothing about how to write shell scripts so they just cannot update them.

I didn't add any flag. This comparison is unfair because what I did is
a rewrite. I can't rewrite one flag at a time.

I believe there are shell completers for argparse (zsh or fish). If the
manually rewritten is too behind and unmaintainable, it's ok to switch
to a generic one.

> 3 and 4. Taking the 2 sentences apart changes the original meaning. ```getopt``` is the most widely accepted way to parse command lines flags for the stdlib of most ``main-stream'' lang is heavily influnced by C-lang. F. I. ruby(```GetoptLong```) and PHP.  In the document ```getopt``` has not been labeled with deprecated, so there's no reason to call ```argparse``` more ``standard'' than ```getopt```.
> What library nowaday pythonists love do not really matter here because those one know js and as3 can contribute even more in this project.
> 
> JS and as3 don't have ```getopt``` in their stdlib because they are not designed to communicate with command line. Those who only know js or as3 can contribute because ```you-get``` is not pythonic in general, not a certain library.

So switching to argparse doesn't affect their ability to contribute to
this project.

Why do you emphesis on "pythonic"? Does a pythonic code base hinder
outside contributors? What hinders me is you-get needs a rewrite to
introduce optional requests and aria2 features. And you-get "commons"
API needs documentation. It's not about code style, it's the normal path
to expand and be better.

-- 
Best regards,
lilydjwg

**Comment by lilydjwg** [comment]
On Wed, Sep 13, 2017 at 04:45:53PM +0000, rosynirvana wrote:
> This patch is premature and personal taste.

Yes it is. But will there be any rewrite that doesn't begin premature?

> We DO have a problem about command line flags. Users can set a default HTTP proxy in their system and specified a socks proxy with comandline flags. I hope we can clean up these real problem affecting any non-develop users in China mainland, then split the project to a command line interface and a library. At that time you guys love ```argparse``` can make the move at your wish.

Unfortunately it's not done yet. IMO being a command line tool is good enough.

-- 
Best regards,
lilydjwg

**Comment by rosynirvana** [comment]
emmm I can find no point to continue this *discussion*.
@soimort Please put an end to this by announcing your decision.

**Comment by UlyssesWu** [comment]
I just wanted to use the cookie feature but I found I can't. No matter what plan you finally choose I hope this issue can be fixed soon.
Excellent debate BTW, though I don't know much about python. 👍

**Comment by ShadowRZ** [comment]
Any further discussion ???

**Comment by rosynirvana** [comment]
I won't call this a *discussion* .
If you wanna to solve this problem, try revert to https://github.com/soimort/you-get/commit/262b6951c6072ecf7f5570296ca14e0789be1dfd as previously mentioned.

**Comment by ShadowRZ** [comment]
Lock this issue.
Any discussion is useless.
