### ISSUE TITLE
you-get 解析结果的提取及其输出格式建议

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#647]
现在获取解析结果并且不下载的方法是
you-get -u URL
这就需要写正则表达式来提取结果了，本人的正则表达式比较弱菜，哪位前辈写过正则表达式提取结果的能否分享下code？

建议把you-get -u URL采用json或dict的方式输出，这样方便其他程序调用

**Comment by cnbeining** [comment]
Check: https://github.com/sceext2/you_get

我和作者聊过，他的意思是you-get的输出偶尔让人摸不清头脑，所以没法提pull request.

而且多清晰度也没确定。

这个还是各个主要贡献者坐下来一起聊聊，确定格式后比较好。

@soimort @sceext

**Comment by redstoneleo** [comment]
我写了个正则表达式来匹配文件名和urls

'''
match = re.search(
    r'title:\s*(?P<fileName>.+?)\s+stream.+?Real URLs:\s+(?P<videoUrls>.+)', s, re.DOTALL | re.IGNORECASE)  #
print(match)

if match:
    d = match.groupdict()


print(d)
'''

**Comment by zhangn1985** [comment]
r如果所有的site都使用VideoExtractor实现，就没有这个问题了。比如说你要拿youku的，就import youku
perpare/extractor运行一下就能得到url了。
you-get -u 并不是这个让你拿URL的。如果你要嵌入到非python的代码里面，那就另说了。

**Comment by redstoneleo** [comment]
@zhangn1985 大哥，能给个你说的import youku的代码例子吗？
为什么我的出现这种情况？
>>> import youku
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import youku
ImportError: No module named 'youku'

**Comment by zhangn1985** [comment]
@redstoneleo 如果你的you-get已经在python3的搜索路径里面。你可以
```
from you-get.extractors import Youku
site = Youku()
```

**Comment by redstoneleo** [comment]
@zhangn1985 应该是from you_get.extractors import Youku 才对，大哥接下来怎么传入url啊？希望传授通过你说的方法获取到you-get -u的结果，谢谢！

**Comment by zhangn1985** [comment]
```
site.url = "http://v.youku.com/v_show/id_XMTMzOTc0ODc0OA==_ev_1.html"
site.prepare()
#z这步应该查询site.stream_stored，以确保下面的Stream_id为有效值
site.extractor(stream_id = ????)
print(site.streams[stream_id]['src])
```
我只知道如果用了VideoExtractor的site，其streams 字典对应stream_id的src项就是真正的URL，Real Url也是在这里打出来的呀。

**Comment by zhangn1985** [comment]
打个广告哈，https://github.com/zhangn1985/you-get 已用VideoExtractor 重写，目前完成度超过70%。
预计在下周末会全部完工。

**Comment by redstoneleo** [comment]
@zhangn1985 出问题了，大哥！
'''
>>> from you_get.extractors import Youku

>>> site = Youku()
>>> site.url = "http://v.youku.com/v_show/id_XMTMzOTc0ODc0OA==_ev_1.html"
>>> site.prepare()
>>> site.extractor(stream_id = ????)
SyntaxError: invalid syntax
>>> 
'''

**Comment by zhangn1985** [comment]
╮(╯▽╰)╭

**Comment by sceext2** [comment]
`you-get` 已经增加 `json` 格式输出. 目前只对使用 `VideoExtractor` 的 extractor 有效. 
详见 #670

**Comment by sceext2** [comment]
@zhangn1985 使用 `VideoExtractor` 重写 真的 太好了 ! ^_^

**Comment by cnbeining** [comment]
@zhangn1985 Great job.

I will wait until you finish to push new codes...

**Comment by zhangn1985** [comment]
you don't need to wait, you can cherry-pick changes to your fork.

**Comment by cnbeining** [comment]
@soimort @jackyzy823 @zhangn1985 

One question:

Respecting the easier solution provided of contributing in the downstream(one file editing per site if no alias required), considering the nature of immature of the downstream should @zhangn1985 's job of converting the old code into ```VideoExtractor``` finish in the future, shall we merge the downstream into the main branch completely one day?

Below are my thoughts, only for reference:

FYI, the ```VideoExtractor``` used in the fork is NOT the same as the one in the main stream. I am afraid this could cause confusion later on; Also, as the main stream updates and new contributions being made,  should new contributors not starting to use ```VideoExtractor``` now, the pressure for the downstream could be too heavy for one man to maintain. 

My point of view is: since only 3 sites in the main stream are currently using  ```VideoExtractor```, it should be possible to merge the code piece of new ```VideoExtractor``` from the downstream to the upstream. This process should be painless. I am hoping this would reduce our works in the future.

**Comment by soimort** [comment]
@cnbeining The main reason I have not yet been using `VideoExtractor` is that: 1) It's still at a very experimental stage, and I don't think it has the best (or even proper) design; 2) I don't want to fix things that ain't broke. As you may find out, the `VideoExtractor` was introduced in July 2014, since then I have added support for a bunch of new sites, but none of them was really implemented in `VideoExtractor`. **Because I want to make `you-get` "just works" for some sites** (that's my whole philosophy on developing it!)

Surely I know of a better design of `VideoExtractor`, it'd be something similar to [this](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/common.py#L49); Then here comes the question: why not just use and contribute to `youtube-dl`, instead of `you-get`? (discussion on this might be too big and does not fit in this issue, so feel free to open another issue and move on there. I'll write more on that later)

For now, thanks to @sceext2's work on #676, we can close this issue.

**Comment by redstoneleo** [comment]
在Python代码里不通过命令行的方式使用you_get并且获得解析结果的代码究竟怎么写啊？希望大大指教下
