### ISSUE TITLE
[youku] --player option no longer works

### ISSUE THREAD

**Issue by univert** [soimort/you-get#796]
If you play youku video using an external player such as mpc-hc. It no longer works.
Previously it worked like other sites.
Is this because youku is expecting "Referer: "Header or youku is expecting cookie?

**Comment by soimort** [comment]
Both.

Your player needs to be able to send arbitrary HTTP requests (with the specified referer) and retrieve the cookies, then stream the raw URLs with those cookies. I don't know of any media player that can easily achieve both of these... unless the player actually is, say, a web browser.

(As a side note: VLC does support cookies via its Lua API. Given that they have [`youtube.lua`](https://github.com/videolan/vlc/blob/master/share/lua/playlist/youtube.lua) already, you could write your own extension like `youku.lua`. But you'll have to do it from scratch, because `you-get` cannot just "pass" the cookies to the player.)

**Comment by linhua55** [comment]
See [comment](https://github.com/soimort/you-get/pull/783#issuecomment-163141741).We can use use the second method to resolve this issue.

**Comment by univert** [comment]
Can we have a proper fix though, just for "--player"? I hate to do a local hack to get this work

**Comment by soimort** [comment]
Probably not, as I just explained.

**Comment by zhangn1985** [comment]
or you can download video to pipe and play video from pipe.
