### ISSUE TITLE
爱奇艺视频合并问题

### ISSUE THREAD

**Issue by superxuxin** [soimort/you-get#828]
you-get --format=high http://www.iqiyi.com/v_19rrn6dwus.html

合并完之后的mp4只包含部分f4v文件，用ffmpeg手动合并没有问题

谢谢！

**Comment by soimort** [comment]
Duplicate of #767.

**Comment by Cappuccin0** [comment]
碰到了类似的问题，按照#767 里面的建议强制不merge，但是下载又有了问题。如下log，下载失败后再重新下载直接变成覆盖而不是续传了。

> ➜  Downloads  youget --no-merge http://www.iqiyi.com/v_19rrl9yiws.html
site:                爱奇艺 (Iqiyi)
title:               奇葩来了之第三季奇葩凶猛出街 高晓松再遭表白
stream:
    - format:        fullhd
      container:     f4v
      video-profile: 全高清
      size:          1238.0 MiB (1298164909 bytes)
    # download-with: you-get --format=fullhd [URL]
>
> Downloading 奇葩来了之第三季奇葩凶猛出街 高晓松再遭表白.f4v ...
 72.5% (897.4/1238.0MB) ├█████████████████████████████████████████████████████████████████████████████████████████████████████████████████───────────────────────────────────────────┤[8/10] 10202 MB/ 82.9% (1026.5/1238.0MB) ├████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████────────────────────────────┤[9/10] 5517 MB/ 89.6% (1109.7/1238.0MB) ├███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████─────────────────┤[10/10] 2337 MB/s
>
> ➜  Downloads  youget --no-merge http://www.iqiyi.com/v_19rrl9yiws.html
site:                爱奇艺 (Iqiyi)
title:               奇葩来了之第三季奇葩凶猛出街 高晓松再遭表白
stream:
    - format:        fullhd
      container:     f4v
      video-profile: 全高清
      size:          1238.0 MiB (1298164909 bytes)
    # download-with: you-get --format=fullhd [URL]
>
> Downloading 奇葩来了之第三季奇葩凶猛出街 高晓松再遭表白.f4v ...
  0.3% (  4.0/1238.0MB) ├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤[3/10]    0  B/syou-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by xyuanmu** [comment]
@soimort 爱奇艺的视频下载有效时间是10分钟，能不能解析完后加一个时间验证，如果超过9分钟自动重新解析？这样应该可以避免重新下载覆盖文件的问题。

**Comment by soimort** [comment]
@xyuanmu 理想状态下`--no-merge`是不应该覆盖原有下载的，这一点需要修复。

超时重新解析以前想做（#29），但是需求不太大，大部分网站也不存在时间限制。所以一直没做。

**Comment by nuomi1** [comment]
@soimort 超时问题在爱奇艺比较严重。
有时下载视频，到 5 / 5（最后一个）时，进度条跳到 0% 重新开始，不知道是不是和这个有关。

**Comment by soimort** [comment]
@nuomi1 我这边网络基本上ping不通iqiyi，没法测试。

谁解决了的话发个PR吧。

```
$ ping www.iqiyi.com 
PING wsdxtzbjngtxdl01.dns.iqiyi.com (119.188.145.10) 56(84) bytes of data.
^C
--- wsdxtzbjngtxdl01.dns.iqiyi.com ping statistics ---
48 packets transmitted, 0 received, 100% packet loss, time 46999ms
```

**Comment by Token713** [comment]
@superxuxin 

`用ffmpeg手动合并没有问题`
请加下Windows下如何手动FFmpeg合并下载的视频？

**Comment by rosynirvana** [comment]
outdated
