### ISSUE TITLE
can't make install

### ISSUE THREAD

**Issue by nuomi1** [soimort/you-get#831]
OS X 10.11.2, Python 3.2.5 form HomeBrew Bottle, you-get 42676da.

````
python3 setup.py install --user
error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
make: *** [install] Error 1
```

**Comment by soimort** [comment]
This is a [known bug](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md#note-on-pip-install---user) on Homebrew Python with `install --user` option, which was caused by some weird distutils option conflicts (it affects a few distros including OS X Homebrew).
There is also an open Python issue: <http://bugs.python.org/issue22269>.
