### ISSUE TITLE
Sometimes the download stuck

### ISSUE THREAD

**Issue by 4321qasdfv** [soimort/you-get#965]
My linux device seems to have a bad network connection. Sometimes the download gets stuck and it will not continue anymore.
I use .sh file to download a bunch of videos automatically, but when the download gets stuck it stops working, and I have to manually stop the download and restart it.
Is there any way to solve this problem? Can I put something like download timeout in it? Or auto-retry?
Thanks!

**Comment by soimort** [comment]
Since you're on Linux, `timeout(1)` command will get you exactly what you want.

In most cases, timeout just means...bad connection. It's hard to tell when we should do a retry, when we should just let it throw a timeout exception. Sometimes retrying makes sense. Sometimes throwing a timeout makes more sense, so people know there IS a connection problem. (otherwise it could be looping forever without producing anything useful, if the network really stinks).

So it would be better for you to implement it yourself (in your script), because it's ultimately up to you to decide what kind of retrying logic you want.
